/* Purpose: deterministic known-work percentage/ETA checks without running indexer.
 * Dependencies: existing Node.js standard library. Outputs: PASS logs.
 * Command from file-search root: node tests/check_index_progress.cjs */
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
let now=1000000;
const nodes={};
for(const id of ['overall','indexing','embedding'])for(const suffix of ['','-value','-detail'])
  nodes['progress-'+id+suffix]={removeAttribute(){delete this.value;}};
nodes['progress-errors']={};
const context={window:{},document:{getElementById:id=>nodes[id]},Date:{now:()=>now}};
vm.createContext(context);
vm.runInContext(fs.readFileSync('frontend/index-progress.js','utf8'),context);
const ui=context.window.IndexProgress;
let state={roots:['C:/'],semantic_enabled:true,counts:{files:10,pending:2,error:1,chunks:20,vectors:5},indexer:{mode:'normal',busy:true,queued_embedding_files:400},model:{}};
ui.update(state);
assert.equal(nodes['progress-indexing-value'].textContent,'80.0%');
assert.equal(nodes['progress-embedding-value'].textContent,'25.0%');
assert.equal(nodes['progress-overall-value'].textContent,'43.3%');
assert(nodes['progress-errors'].textContent.includes('1 files failed'));
assert(nodes['progress-embedding-detail'].textContent.includes('5 / 20'));
console.log('PASS: exact file/passage/overall coverage, errors and queues distinct from passages');
now+=30000;state.counts.pending=1;state.counts.vectors=10;ui.update(state);
for(const id of ['overall','indexing','embedding'])assert(nodes['progress-'+id+'-detail'].textContent.includes('Approx.'));
console.log('PASS: recent throughput estimates known remaining work after 30 seconds');
now+=30000;ui.update(state);
for(const id of ['overall','indexing','embedding'])assert(nodes['progress-'+id+'-detail'].textContent.includes('No recent progress'));
state.indexer.mode='paused';ui.update(state);assert(nodes['progress-overall-detail'].textContent.includes('Paused'));
state.indexer.mode='normal';state.indexer.semantic_error='Model unavailable';ui.update(state);
assert(nodes['progress-overall-detail'].textContent.includes('Blocked: Model unavailable'));
assert(nodes['progress-embedding-detail'].textContent.includes('Blocked: Model unavailable'));
delete state.indexer.semantic_error;
console.log('PASS: stalled, paused and model-blocked work never shows a false countdown');
state.counts={files:20,pending:11,chunks:40,vectors:10};ui.update(state);
assert.equal(nodes['progress-indexing-value'].textContent,'45.0%');
assert.equal(nodes['progress-overall-value'].textContent,'31.7%');
state.counts={files:20,pending:0,chunks:40,vectors:40};ui.update(state);
assert.equal(nodes['progress-overall-value'].textContent,'100%');
assert(nodes['progress-overall-detail'].textContent.includes('Checking for more work'));
state.indexer.busy=false;ui.update(state);assert(nodes['progress-overall-detail'].textContent.includes('Known work complete'));
console.log('PASS: growing discovery totals and 100 percent never imply an active scan has finished');
state.counts={files:10,pending:5,chunks:20,vectors:5};state.indexer.busy=true;ui.update(state);
assert(nodes['progress-overall-detail'].textContent.includes('Estimating'));
state.semantic_enabled=false;ui.update(state);
assert.equal(nodes['progress-embedding-value'].textContent,'Disabled');
assert.equal(nodes['progress-overall-value'].textContent,'50.0%');
state.semantic_enabled=true;state.counts={files:0,pending:0,chunks:0,vectors:0};ui.update(state);
assert.equal(nodes['progress-overall-value'].textContent,'No files + passages yet');
assert.equal(nodes['progress-overall'].value,undefined);
state.counts={files:10,pending:5,vectors:3};ui.update(state);
assert.equal(nodes['progress-embedding-value'].textContent,'Unavailable');
assert.equal(nodes['progress-overall-value'].textContent,'Unavailable');
ui.stopped();assert(nodes['progress-overall-detail'].textContent.includes('Worker stopped'));
console.log('PASS: reset, disabled semantics, empty/legacy snapshots and worker stop');
const html=fs.readFileSync('frontend/center.html','utf8');
assert(html.indexOf('src="index-progress.js"')<html.indexOf('src="settings.js"'));
for(const id of Object.keys(nodes))assert(html.includes('id="'+id+'"'));
const settings=fs.readFileSync('frontend/settings.js','utf8');
assert(settings.includes('window.IndexProgress?.update(value)'));
assert(settings.includes('window.IndexProgress?.stopped()'));
console.log('PASS: all accessible UI controls and existing status subscription wired');
